<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Lumina">
      <HintPath>C:\Users\Illidan\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.dll</HintPath>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>C:\Users\Illidan\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.Excel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
