<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Name>GlamourChecker</Name>
        <Author>Dr. Marcos</Author>
        <Punchline>Nunca mais jogue fora uma aparencia que voce nao tem!</Punchline>
        <Description>Verifica seu inventario e alerta sobre equipamentos cujos modelos (aparências) ainda não foram guardados no Glamour Dresser ou Armoire.</Description>
        <RepoUrl>https://github.com/GuiMarcosNogueira/glamour-checker</RepoUrl>
        <Tags>glamour,inventory,utility</Tags>
        <IconUrl>https://guimarcosnogueira.github.io/glamour-checker/images/icon.png</IconUrl>
    </PropertyGroup>

  <ItemGroup>
    <None Include="loc\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Resources\SharedModels.json" />
  </ItemGroup>
</Project>
