name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x' # Using net10.0 as per your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Archive Release
      if: success() && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: GlamourChecker
        path: GlamourChecker/bin/Release/net10.0/GlamourChecker/

    - name: Create Release Zip
      if: success() && github.event_name != 'pull_request'
      run: |
        Compress-Archive -Path GlamourChecker/bin/Release/net10.0/GlamourChecker/* -DestinationPath GlamourChecker-latest.zip
        
    - name: Publish Release artifact
      if: success() && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: GlamourChecker-Release-Zip
        path: GlamourChecker-latest.zip
